---
title: "Multivariate Analysis: Lecture 5"
format: html
---

## Exercise 5.1

```{r}
bears <- load("~/GitHub/Multivariate-Analysis/Multivariate_Analysis/Lecture_5/J_WEx5.9.Rdata")
```

### Question 1

```{r}
#large sample 95% simultaneous confidence intervals 
p <- length(xbar)
n <- 61

#Using alpha = 5%
alpha <- 0.05
chisq <- qchisq(1- alpha, p)

#Weight
a1 <- matrix(c(1,0,0,0,0,0), nrow = 6)
lower1 <- t(a1)%*%xbar - sqrt(chisq)*sqrt((t(a1)%*%S%*%a1)/n)
upper1 <- t(a1)%*%xbar + sqrt(chisq)*sqrt((t(a1)%*%S%*%a1)/n)
lower1 ; upper1

#Body length
a2 <- matrix(c(0,1,0,0,0,0), nrow = 6)
lower2 <- t(a2)%*%xbar - sqrt(chisq)*sqrt((t(a2)%*%S%*%a2)/n)
upper2 <- t(a2)%*%xbar + sqrt(chisq)*sqrt((t(a2)%*%S%*%a2)/n)
lower2 ; upper2

#Neck
a3 <- matrix(c(0,0,1,0,0,0), nrow = 6)
lower3 <- t(a3)%*%xbar - sqrt(chisq)*sqrt((t(a3)%*%S%*%a3)/n)
upper3 <- t(a3)%*%xbar + sqrt(chisq)*sqrt((t(a3)%*%S%*%a3)/n)
lower3 ; upper3

#Girth
a4 <- matrix(c(0,0,0,1,0,0), nrow = 6)
lower4 <- t(a4)%*%xbar - sqrt(chisq)*sqrt((t(a4)%*%S%*%a4)/n)
upper4 <- t(a4)%*%xbar + sqrt(chisq)*sqrt((t(a4)%*%S%*%a4)/n)
lower4 ; upper4

#Head length
a5 <- matrix(c(0,0,0,0,1,0), nrow = 6)
lower5 <- t(a5)%*%xbar - sqrt(chisq)*sqrt((t(a5)%*%S%*%a5)/n)
upper5 <- t(a5)%*%xbar + sqrt(chisq)*sqrt((t(a5)%*%S%*%a5)/n)
lower5 ; upper5

#Head width
a6 <- matrix(c(0,0,0,0,0,1), nrow = 6)
lower6 <- t(a6)%*%xbar - sqrt(chisq)*sqrt((t(a6)%*%S%*%a6)/n)
upper6 <- t(a6)%*%xbar + sqrt(chisq)*sqrt((t(a6)%*%S%*%a6)/n)
lower6 ; upper6

```

### Question 2

```{r}
#large sample 95% simultaneous confidence intervals 
p <- 2

#Using alpha = 5%
alpha <- 0.05
chisq <- qchisq(1- alpha, p) #chi-squared stat 

#Extract means
x1 <- xbar[1]
x2 <- xbar[4]
xbar12 <- matrix(c(x1, x2), nrow = 2)

#Extract variance and covariance 
S11 <- S[1,1]
SS <- S[1,4]
S22 <- S[4,4]
S12 <- matrix(c(S11, SS, SS, S22), nrow = 2)

#S inverse
S_inv <- solve(S12)

#Eigen values 
eigen <- eigen(S12)

#Axis lengths
(axis1length <- sqrt(eigen$values[1])*sqrt(chisq/n))
(axis2length <- sqrt(eigen$values[2])*sqrt(chisq/n))

#Axis ratios
(axisratio <- sqrt(eigen$values[1])/sqrt(eigen$values[2]))

#Draw the ellipse, same as in textbook
par(mfrow=c(1,1))
phi <- atan2(eigen$vectors[2, 1], eigen$vectors[1, 1]) # angle of major axis
t <- seq(0, 2*pi, 0.01) 
xx <- xbar12[1] + axis1length*cos(t)*cos(phi) - axis2length*sin(t)*sin(phi)
yy <- xbar12[2] + axis1length*cos(t)*sin(phi) + axis2length*sin(t)*cos(phi)
plot(xx, yy, type = 'l', lwd = 2.5, xlab = '', ylab = '') ; title(xlab = bquote(bar(x)[1]), line = 0.2) ; title(ylab = bquote(bar(x)[2]), line = 0) ; lines(c(xbar12[1], xbar12[1]), c(0, xbar12[2]), lty = 5) ; lines(c(0, xbar12[1]), c(xbar12[2], xbar12[2]), lty = 5)


mjrx <- xbar12[1] + c(-1, 1)*axis1length*cos(phi)
mjry <- xbar12[2] + c(-1, 1)*axis1length*sin(phi)
mnrx <- xbar12[1] + c(-1, 1)*axis2length*cos(phi + pi/2) #axes are always orthogonal!
mnry <- xbar12[2] + c(-1, 1)*axis2length*sin(phi + pi/2)

lines(mjrx, mjry, lwd = 2)
lines(mnrx, mnry, lwd = 2)
```

### Question 3

```{r}
alpha <- 0.05
p <- length(xbar)
n <- 61

tstat <- qt(1-alpha/(2*p), n - 1)

#Weight
a1 <- matrix(c(1,0,0,0,0,0), nrow = 6)
upper1 <- t(a1)%*%xbar + tstat*sqrt(S[1,1]/n)
lower1 <- t(a1)%*%xbar - tstat*sqrt(S[1,1]/n)
lower1 ; upper1

#Body length
a2 <- matrix(c(0,1,0,0,0,0), nrow = 6)
upper2 <- t(a2)%*%xbar + tstat*sqrt(S[2,2]/n)
lower2 <- t(a2)%*%xbar - tstat*sqrt(S[2,2]/n)
lower2 ; upper2

#Neck
a3 <- matrix(c(0,0,1,0,0,0), nrow = 6)
upper3 <- t(a3)%*%xbar + tstat*sqrt(S[3,3]/n)
lower3 <- t(a3)%*%xbar - tstat*sqrt(S[3,3]/n)
lower3 ; upper3

#Girth
a4 <- matrix(c(0,0,0,1,0,0), nrow = 6)
upper4 <- t(a4)%*%xbar + tstat*sqrt(S[4,4]/n)
lower4 <- t(a4)%*%xbar - tstat*sqrt(S[4,4]/n)
lower4 ; upper4

#Head length
a5 <- matrix(c(0,0,0,0,1,0), nrow = 6)
upper5 <- t(a5)%*%xbar + tstat*sqrt(S[5,5]/n)
lower5 <- t(a5)%*%xbar - tstat*sqrt(S[5,5]/n)
lower5 ; upper5

#Head width
a6 <- matrix(c(0,0,0,0,0,1), nrow = 6)
upper6 <- t(a6)%*%xbar + tstat*sqrt(S[6,6]/n)
lower6 <- t(a6)%*%xbar - tstat*sqrt(S[6,6]/n)
lower6 ; upper6
```

### Question 4

```{r}
#Plot
plot(xx, yy, type = 'l', lwd = 2.5, xlab = bquote(mu[1]), ylab = bquote(mu[2]), 
     xlim = range(c(xx, lower1, upper1)),
     ylim = range(c(yy, lower4, upper4)))

lower1 <- as.numeric(lower1)
upper1 <- as.numeric(upper1)
lower4 <- as.numeric(lower4)
upper4 <- as.numeric(upper4)

#lines(c(0, lower1), c(upper4, upper4), lty = 5, col = "red")
#lines(c(0, upper1), c(lower4, lower4), lty = 5, col = "red")
#lines(c(lower1, lower1), c(0, upper4), lty = 5, col = "red")
#lines(c(upper1, upper1), c(0, upper4), lty = 5, col = "red")

#Draw rectangle 
rect(lower1, lower4, upper1, upper4, border = "red", lwd = 2, lty = 2)
```

### Question 5

```{r}
alpha <- 0.05
m <- 6 + 1
alpha_new <- alpha/m
n <- 61

tstat <- qt(1-alpha/(2*m), n - 1)

#Difference 
aa <- matrix(c(0,0,0,0,-1,1), nrow = 6)
upper <- t(aa)%*%xbar + tstat*sqrt((S[6,6] + S[5,5] - 2*S[5,6])/n)
lower <- t(aa)%*%xbar - tstat*sqrt((S[6,6] + S[5,5] - 2*S[5,6])/n)
upper ; lower

```

## Exercise 5.2

```{r}
rm(list = ls())
grizz <- read.table("~/GitHub/Multivariate-Analysis/Multivariate_Analysis/Lecture_5/T1-4.txt")
```

### Question 1

```{r}
library(tidyverse)
len <- grizz[,c(5,6,7,8)]
wt <- grizz[,c(1,2,3,4)]
xbar_len <- len |>
  summarise(
    xbar2 = mean(len[,1]),
    xbar3 = mean(len[,2]),
    xbar4 = mean(len[,3]),
    xbar5 = mean(len[,4])
  )
xbar_len <- as.numeric(xbar_len)

#Covariance matrix
S_len <- cov(len)

## 95% Simultaneous T^2 Intervals
alpha <- 0.05
n <- nrow(len)
p <- ncol(len)
fstat <- qf(1 - alpha, p, n-p)
c2 <- ((p*(n-1))/(n-p))*fstat


mu2_lower <- xbar_len[1] - sqrt(c2)*sqrt(S_len[1,1]/n)
mu2_upper <- xbar_len[1] + sqrt(c2)*sqrt(S_len[1,1]/n)
mu2_lower ; mu2_upper

mu3_lower <- xbar_len[2] - sqrt(c2)*sqrt(S_len[2,2]/n)
mu3_upper <- xbar_len[2] + sqrt(c2)*sqrt(S_len[2,2]/n)
mu3_lower ; mu3_upper

mu4_lower <- xbar_len[3] - sqrt(c2)*sqrt(S_len[3,3]/n)
mu4_upper <- xbar_len[3] + sqrt(c2)*sqrt(S_len[3,3]/n)
mu4_lower ; mu4_upper

mu5_lower <- xbar_len[4] - sqrt(c2)*sqrt(S_len[4,4]/n)
mu5_upper <- xbar_len[4] + sqrt(c2)*sqrt(S_len[4,4]/n)
mu5_lower ; mu5_upper
```

### Question 2

```{r}
#2-to-3
x23 <- xbar_len[2] - xbar_len[1]
lower23 <- x23 - sqrt(c2)*sqrt((S_len[1,1] + S_len[2,2] - 2*S_len[1,2])/n)
upper23 <- x23 + sqrt(c2)*sqrt((S_len[1,1] + S_len[2,2] - 2*S_len[1,2])/n)
lower23 ; upper23

#3-to-4
x34 <- xbar_len[3] - xbar_len[2]
lower34 <- x34 - sqrt(c2)*sqrt((S_len[2,2] + S_len[3,3] - 2*S_len[2,3])/n)
upper34 <- x34 + sqrt(c2)*sqrt((S_len[2,2] + S_len[3,3] - 2*S_len[2,3])/n)
lower34 ; upper34

#4-to-5
x45 <- xbar_len[4] - xbar_len[3]
lower45 <- x45 - sqrt(c2)*sqrt((S_len[3,3] + S_len[4,4] - 2*S_len[3,4])/n)
upper45 <- x45 + sqrt(c2)*sqrt((S_len[3,3] + S_len[4,4] - 2*S_len[3,4])/n)
lower45 ; upper45
```

### Question 3

```{r}
A <- matrix(c(-1,1,0,0,0,0,-1,1), nrow = 2, byrow = T)
xbar <- A%*%xbar_len
S_A <- A%*%S_len%*%t(A)

eigen <- eigen(S_A)
par(mfrow=c(1,1))

#Axis lengths
(axis1length <- sqrt(eigen$values[1])*sqrt(c2/n))
(axis2length <- sqrt(eigen$values[2])*sqrt(c2/n))

phi <- atan2(eigen$vectors[2, 1], eigen$vectors[1, 1]) # angle of major axis
t <- seq(0, 2*pi, 0.01) 
xx <- xbar[1] + axis1length*cos(t)*cos(phi) - axis2length*sin(t)*sin(phi)
yy <- xbar[2] + axis1length*cos(t)*sin(phi) + axis2length*sin(t)*cos(phi)

#Plot
plot(xx, yy, type = 'l', lwd = 2.5, xlab = bquote(mu[3] - mu[2]), ylab = bquote(mu[5] - mu[4]))
points(xbar[1], xbar[2], pch = 16)

```

### Question 4

```{r}
## 95% Bonferroni CI 
alpha <- 0.05
n <- 61
p <- 6
m <- 7

tstat <- qt(1-alpha/(2*m), n - 1)

# Year 2
mu2_lower <- xbar_len[1] - tstat*sqrt(S_len[1,1]/n)
mu2_upper <- xbar_len[1] + tstat*sqrt(S_len[1,1]/n)
round(mu2_lower,3) ; round(mu2_upper,3)

# Year 3
mu3_lower <- xbar_len[2] - tstat*sqrt(S_len[2,2]/n)
mu3_upper <- xbar_len[2] + tstat*sqrt(S_len[2,2]/n)
mu3_lower ; mu3_upper

# Year 4
mu4_lower <- xbar_len[3] - tstat*sqrt(S_len[3,3]/n)
mu4_upper <- xbar_len[3] + tstat*sqrt(S_len[3,3]/n)
mu4_lower ; mu4_upper

# Year 5
mu5_lower <- xbar_len[4] - tstat*sqrt(S_len[4,4]/n)
mu5_upper <- xbar_len[4] + tstat*sqrt(S_len[4,4]/n)
mu5_lower ; mu5_upper



#2-to-3
x23 <- xbar_len[2] - xbar_len[1]
lower23 <- x23 - tstat*sqrt((S_len[1,1] + S_len[2,2] - 2*S_len[1,2])/n)
upper23 <- x23 + tstat*sqrt((S_len[1,1] + S_len[2,2] - 2*S_len[1,2])/n)
lower23 ; upper23

#3-to-4
x34 <- xbar_len[3] - xbar_len[2]
lower34 <- x34 - tstat*sqrt((S_len[2,2] + S_len[3,3] - 2*S_len[2,3])/n)
upper34 <- x34 + tstat*sqrt((S_len[2,2] + S_len[3,3] - 2*S_len[2,3])/n)
lower34 ; upper34

#4-to-5
x45 <- xbar_len[4] - xbar_len[3]
lower45 <- x45 - tstat*sqrt((S_len[3,3] + S_len[4,4] - 2*S_len[3,4])/n)
upper45 <- x45 + tstat*sqrt((S_len[3,3] + S_len[4,4] - 2*S_len[3,4])/n)
lower45 ; upper45
```

### Question 5

```{r}
plot(xx, yy, type = 'l', lwd = 2.5, xlab = bquote(mu[3] - mu[2]), ylab = bquote(mu[5] - mu[4]))
points(xbar[1], xbar[2], pch = 16)
rect(lower23, lower45, upper23, upper45, border = "red", lwd = 2, lty = 2)

```
