---
title: "Quiz 5"
format: html
---

## Question 1

```{r}
rm(list = ls())
bears <- load("~/GitHub/Multivariate-Analysis/Multivariate_Analysis/Lecture_5/J_WEx5.9.Rdata")

# We already have xbar and S
#Null hypothesis 
h0 <- matrix(c(95,160,55,93,18,31), nrow = 6)
xbar <- as.matrix(xbar)
S <- as.matrix(S)

n <- 61
p <- nrow(xbar)

# Hotelling's T^2 
T2 <- n*t(xbar - h0)%*%solve(S)%*%(xbar-h0)
round(T2, 3)

# p-value
pval <- 1 - pf(T2*(n-p)/((n-1)*p), p, n-p)
round(pval, 3) 

# wilk's lambda
Wlambda <- (1 + T2/(n-1))^-1
round(Wlambda, 3)
```

## Question 2

```{r}
#CI for Head length
p <- length(xbar)
n <- 61
alpha <- 0.05
chisq <- qchisq(1- alpha, p)
fstat <- qf(1 - alpha, p, n-p)
c2 <- ((p*(n-1))/(n-p))*fstat

a5 <- matrix(c(0,0,0,0,1,0), nrow = 6)

# Exact distribution 
lower <- t(a5)%*%xbar - sqrt(c2)*sqrt((t(a5)%*%S%*%a5)/n)
upper <- t(a5)%*%xbar + sqrt(c2)*sqrt((t(a5)%*%S%*%a5)/n)
round(lower, 3) ; round(upper , 3)

#large sample 95% simultaneous confidence intervals 
lower5 <- t(a5)%*%xbar - sqrt(chisq)*sqrt((t(a5)%*%S%*%a5)/n)
upper5 <- t(a5)%*%xbar + sqrt(chisq)*sqrt((t(a5)%*%S%*%a5)/n)
round(lower5, 3) ; round(upper5, 3)
```

## Question 3

```{r}
#95% Bonferroni confidencwe intervals
alpha <- 0.05
p <- length(xbar)
n <- 61

tstat <- qt(1-alpha/(2*p), n - 1)

#Neck
a3 <- matrix(c(0,0,1,0,0,0), nrow = 6)
upper3 <- t(a3)%*%xbar + tstat*sqrt(S[3,3]/n)
lower3 <- t(a3)%*%xbar - tstat*sqrt(S[3,3]/n)
round(lower3, 3) ; round(upper3,3)
```

## Question 4

```{r}
#6D ellipsoid for confidence region 
eig_S <- eigen(S)

#Longest axis half-length
round(sqrt(eig_S$values[1])*sqrt(c2/n), 3)
round(sqrt(eig_S$values[1]*c2/n), 3)

#Shortest axis half-length
round(sqrt(eig_S$values[6]*c2/n), 3)
```

## Question 5

```{r}

```
