---
title: "Continuous Assessment 3"
author: "Isabella Lethbridge and Hayden Lakey"
date: "8 March 2026"
format: pdf
---

## Question 1

Let $X \sim N_p(\mu, \Sigma) \ with \ |\Sigma| > 0$.

RTP:

$$
(X - \mu)'\Sigma^{-1}(X - \mu) \sim \chi^2_p 
$$

Using the eigen decomposition of $\Sigma$:

$$
\Sigma = U\Lambda U^{'} 
$$ where $U$ is an orthogonal matrix, such that\
$$
U^{'} = U^{-1}
$$

Then $$
\Sigma^{-1} = (U\Lambda U^{'})^{-1} 
= (U^{'})^{-1} \Lambda^{-1} U^{-1} 
= U\Lambda^{-1} U^{'} 
$$

Substituting in $\Sigma^{-1}$ $$
\begin{aligned}
(X - \mu)'\Sigma^{-1}(X - \mu)
&= (X - \mu)^{'} U\Lambda^{-1} U^{'}(X - \mu) \\
&= (X - \mu)^{'}U\Lambda^{-\frac{1}{2}} \Lambda^{-\frac{1}{2}} U^{'}(X - \mu)
\end{aligned}
$$

Let $$
Y = \Lambda^{-\frac{1}{2}} U^{'}(X - \mu)
$$

and let $$
A = \Lambda^{-\frac{1}{2}} U^{'}
$$

Therefore $$
Y = A(X - \mu) \sim N_p(0, A\Sigma A^{'}) 
$$

Solve for the Covariance matrix of $Y$ $$
\begin{aligned}
A\Sigma A^{'}
&= (\Lambda^{-\frac{1}{2}} U^{'}) \ \Sigma \ (\Lambda^{-\frac{1}{2}} U^{'})^{'} \\
&= (\Lambda^{-\frac{1}{2}} U^{'}) \ \Sigma \ U(\Lambda^{-\frac{1}{2}} )^{'} \\
&= \Lambda^{-\frac{1}{2}} U^{'} \ U\Lambda U^{'} \ U(\Lambda^{-\frac{1}{2}})^{'} \\
&= \Lambda^{-\frac{1}{2}} \Lambda \ (\Lambda^{-\frac{1}{2}})^{'} \\
&= I_p
\end{aligned}
$$

$Y$ has a Multivariate Standard Normal Distribution.\
$$
Y \sim N_p(0, I_p)
$$

This means that individual $Y_i$ components have a Standard Normal Distribution. $$
Y_i \sim N(0, 1)
$$

The Sum of Squares of independent Standard Normal variables has a Chi-squared Distribution with $p$ degrees of freedom. $$
Y^{'}Y = \sum^{p}_{i = 1} Y^{2}_i
$$

$$
\sum^{p}_{i = 1} Y^{2}_i \sim \chi^{2}_p
$$

Since $$
(X - \mu)'\Sigma^{-1}(X - \mu) = Y^{'}Y 
$$ We have that $$
(X - \mu)'\Sigma^{-1}(X - \mu) \sim \chi^2_p
$$

\newpage

## Question 2

We are given $\mu$ defined as $$
\mu = 
\begin{bmatrix}
5 \\
0 \\
-2\\
6 \\
2
\end{bmatrix}
$$ Rearranging the rows to how X1 and X2 are defined, results in two $\mu$ vectors $$
\mu_{1} =
\begin{bmatrix}
5 \\
0 \\
6 
\end{bmatrix}
\quad
\mu_{2} = 
\begin{bmatrix}
-2 \\
2
\end{bmatrix}
$$

$$
\Sigma = 
\begin{bmatrix}
8 & 3 & 0 & -1 & 5 \\
3 & 12 & 2 & 2 & -2 \\
0 & 2 & 8 & 0 & 2 \\
-1 & 2 & 0 & 9 & 1 \\
5 & -2 & 2 & 1 & 10
\end{bmatrix}
$$ $\Sigma$ is partitioned such that, $$
\Sigma_{11} =
\begin{bmatrix}
8 & 3 & 0 \\
3 & 12 & 2 \\
0 & 2 & 8
\end{bmatrix}
\quad
\Sigma_{12} =
\begin{bmatrix}
-1 & 5 \\
2 & -2 \\
0 & 2
\end{bmatrix}
\quad
\Sigma_{21} =
\begin{bmatrix}
-1 & 2 & 0 \\
5 & -2 & 2 
\end{bmatrix}
\quad
\Sigma_{22} =
\begin{bmatrix}
9 & 1 \\
1 & 10 
\end{bmatrix}
$$ To calculate the value of $\mu_{1 \mid 2}$ we use $$
\mu_{1 \mid 2} = \mu_{1} + \Sigma_{12}\Sigma_{22}^{-1}(x_{2} - \mu_{2})
$$ \clearpage From this we now just need to calculate the values of $(x_{2} - \mu_{2})$ and $\Sigma_{22}^{-1}$:

$$
x_{2} - \mu_{2} = 
\begin{bmatrix}
-1 \\
2
\end{bmatrix}
\quad
-
\quad
\begin{bmatrix}
-2 \\
2
\end{bmatrix}
\quad
=
\quad
\begin{bmatrix}
1 \\
0
\end{bmatrix}
\quad
$$ The inverse of $\Sigma_{22}$ is $$
\Sigma_{22}^{-1} = 
\begin{bmatrix}
\dfrac{10}{89} & -\dfrac{1}{89} \\
-\dfrac{1}{89} & \dfrac{9}{89} 
\end{bmatrix}
$$ Now that we have values for all the parameters, $\mu_{1 \mid 2}$ can easily be computed to give us: $$
\mu_{1 \mid 2} = 
\begin{bmatrix}
\dfrac{430}{89}\\
\dfrac{22}{89} \\
\dfrac{532}{89}
\end{bmatrix}
$$ To get the covariance matrix we use the formula: $\Sigma_{1 \mid 2} = \Sigma_{11} - \Sigma_{12}\Sigma_{22}^{-1}\Sigma_{21}$

Resulting in a 3x3 matrix: $$
\Sigma_{1 \mid 2} =
\begin{bmatrix}
\dfrac{467}{89} & \dfrac{389}{89} & -\dfrac{92}{89} \\
\dfrac{389}{89} & \dfrac{984}{89} & \dfrac{218}{89} \\
-\dfrac{92}{89} & \dfrac{218}{89} & \dfrac{676}{89}
\end{bmatrix}
$$ We now have all the elements for the conditional (joint) distribution $$
X_{1}\mid X_{2} =
\begin{bmatrix}
-1 \\
2
\end{bmatrix}
\sim
N_{3}(\mu_{1 \mid 2}, \Sigma_{1 \mid 2})
$$

The conditional (joint) distribution now can be written as,

$$
X_{1}\mid X_{2} =
\begin{bmatrix}
-1 \\
2
\end{bmatrix}
\sim
N_{3}
(
\begin{bmatrix}
\dfrac{430}{89}\\
\dfrac{22}{89} \\
\dfrac{532}{89}
\end{bmatrix}
,
\quad
\begin{bmatrix}
\dfrac{467}{89} & \dfrac{389}{89} & -\dfrac{92}{89} \\
\dfrac{389}{89} & \dfrac{984}{89} & \dfrac{218}{89} \\
-\dfrac{92}{89} & \dfrac{218}{89} & \dfrac{676}{89}
\end{bmatrix}
)
$$ Simplified: $$
X_{1}\mid X_{2} =
\begin{bmatrix}
-1 \\
2
\end{bmatrix}
\sim
N_{3}
(
\begin{bmatrix}
4.831\\
0.247 \\
5.978
\end{bmatrix}
,
\quad
\begin{bmatrix}
5.247 & 4.371 & -1.034 \\
4.371 & 11.056 & 2.449 \\
-1.034 & 2.449 & 7.596
\end{bmatrix}
)
$$
