---
title: "Multivariate Analysis: Lecture 1 Homework"
format: html
editor: visual
---

## Exercise 1

### Question 1

```{r}
#Create matrix
(X <- matrix(c(9, 5, 1, 1, 3, 2), nrow = 3))

#Create vector of 1's 
One <- matrix(c(1,1,1))

#Convert to dataframe
X_dat <- as.data.frame(X, row.names = c("x1", "x2", "x3"))

#Plot in 2D 
plot(X_dat, col = "black", pch = 16)

#Calculate mean
(X_bar <- 1/n*t(X)%*%One)

#Save X_bar and X as dataframe 
X_plot <- as.data.frame(rbind(X, t(X_bar)))

#Add mean to plot 
plot(X_plot, col = "black", pch = 16)
```

### Question 2

```{r}
library(plot3D)
plot3D::arrows3D(c(0,0), c(0,0), c(0,0), x1 = X[1,], y1 = X[2,], z1 = X[3,], col = c("purple", "blue"), lwd = 2)

```

### Question 3

```{r}
#Using deviation vectors
cent_X <- scale(X, center = T, scale = F)
(d1 <- matrix(cent_X[,1]))
(d2 <- matrix(cent_X[,2]))

#Plot deviation dectors from origin
plot3D::arrows3D(c(0,0), c(0,0), c(0,0), x1 = c(d1[1], d2[1]), y1 = c(d1[2], d2[2]), z1 = c(d1[3], d2[3]), col = c("purple", "blue"), lwd = 2)

#Length of vectors
(len_d1 <- t(d1)%*%d1)
(len_d2 <- t(d2)%*%d2)

#Cosine of angles between vectors 
(cos_ang <- (sum(d1*d2))/(len_d1*len_d2))

S <- t(X)%*%X-nrow(X)*X_bar%*%t(X_bar)
S

D <- diag(diag(S))
D

R <- sqrt(solve(D))%*%S%*%sqrt(solve(D))
R

```

## Exercise 2

### Question 1

```{r}
X_bar <- matrix(c(0.766, 0.508, 0.438, 0.161))
X_bar

S <- matrix(c(0.856, 0.635, 0.173, 0.096, 0.635, 0.568, 0.128, 0.067, 0.173, 0.128, 0.171, 0.039, 0.096, 0.067, 0.039, 0.043), nrow = 4)
S

#Create vector of 1's
One <- matrix(c(1,1,1,1))

#Sample mean 
Samp_mean <- t(One)%*%X_bar
Samp_mean

#Sample variance 
Samp_var <- t(One)%*%S%*%One
Samp_var
```

### Question 2

```{r}
#Extract means 
pet_mean <- X_bar[1]
natgas_mean <- X_bar[2]

#Excess of means of petroleum consumption over natural gas
pet_mean-natgas_mean

#or...
P <- matrix(c(1, -1, 0, 0))
t(P)%*%X_bar

#Excess of variance of petroleum consumption over natural gas
t(P)%*%S%*%P

#Covariance 
t(One)%*%S%*%P
```

## Exercise 3

```{r}
library(lattice)
library(ggplot2)

#Looking at correlations:
track <- read.csv('NationalTrack.csv', header = T)
head(track)
(R <- cor(track[,2:6]))

library(corrplot)
corrplot(R, method='circle')
corrplot(R, method='number')

```
